from ultron_branding import install_ultron_branding
install_ultron_branding()

from ultron_ctk_compat import install_customtkinter_compat
from ultron_identity import install_identity_patch
from ultron_vision import install_vision_patch
from ultron_health import install_health_patch
from ultron_focus import install_focus_patch
from ultron_awareness import install_awareness_patch
from ultron_bilingual import install_bilingual_patch
from ultron_files import install_file_intelligence_patch
from ultron_planner import install_planner_patch
from ultron_windows import install_window_control_patch
from ultron_permissions import install_permission_patch
from ultron_memory_categories import install_memory_category_patch
from ultron_updater import install_update_check_patch
from ultron_action_history import install_action_history_patch
from ultron_router_v2 import install_router_v2_patch
from ultron_recovery import install_recovery_patch
from ultron_performance import install_performance_patch
from ultron_visual_actions import install_visual_action_patch
from ultron_screen_state import install_screen_state_patch
from ultron_activity import install_activity_patch
from ultron_skills_v2 import install_skills_v2_patch
from ultron_skills_runtime_v4 import install_skills_runtime_v4
from ultron_profiles_v5 import install_profiles_v5
from ultron_release_v5 import install_release_v5
from ultron_nvidia import install_nvidia_patch

for patch in (install_customtkinter_compat,install_identity_patch,install_vision_patch,install_health_patch,install_focus_patch,install_awareness_patch,install_bilingual_patch,install_file_intelligence_patch,install_planner_patch,install_window_control_patch,install_permission_patch,install_memory_category_patch,install_update_check_patch,install_action_history_patch,install_router_v2_patch,install_recovery_patch,install_performance_patch,install_visual_action_patch,install_screen_state_patch,install_activity_patch,install_skills_v2_patch,install_skills_runtime_v4,install_profiles_v5,install_release_v5,install_nvidia_patch): patch()

import ultron_main
from ultron_ui_v3 import install_ui_v3
from ultron_brain_ui_v3 import install_brain_ui_v3
from ultron_ux_v3 import install_ux_v3
from ultron_voice_state_v3 import install_voice_state_v3
from ultron_control_center_v4 import install_control_center_v4
from ultron_palette_v4 import install_palette_v4
from ultron_resilience_v4 import install_resilience_v4
from ultron_neural_timeline_v4 import install_neural_timeline_v4
from ultron_visual_settings_v4 import install_visual_settings_v4
from ultron_centers_v4 import install_centers_v4
from ultron_brain_v4 import install_brain_v4
from ultron_diagnostics_v5 import install_diagnostics_v5
from ultron_notifications_v5 import install_notifications_v5
from ultron_home_v5 import install_home_v5
from ultron_overlay import install_overlay
from ultron_watch import install_watch_mode
from ultron_conversation import install_conversation_mode
from ultron_command_center import install_command_center
from ultron_permission_ui import install_permission_ui
from ultron_runtime_v2 import install_runtime_v2
from ultron_brain_v2 import install_brain_v2

for patch in (install_ui_v3,install_overlay,install_watch_mode,install_conversation_mode,install_command_center,install_permission_ui,install_runtime_v2,install_brain_ui_v3,install_ux_v3,install_voice_state_v3,install_control_center_v4,install_palette_v4,install_resilience_v4,install_neural_timeline_v4,install_visual_settings_v4,install_centers_v4,install_brain_v4,install_diagnostics_v5,install_notifications_v5,install_home_v5): patch(ultron_main.UltronApp)
install_brain_v2()

if __name__ == "__main__":
    app=ultron_main.UltronApp(); app.mainloop()
